"""
页面生成器 - 自动生成 HTML 页面
"""
import os
import re
from datetime import datetime
from jinja2 import Template
from config import SITE_REPO_PATH, TEMPLATES_DIR

# 基础页面模板
BASE_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ title }} | Outbound Guide</title>
  <meta name="description" content="{{ description }}" />
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    html{scroll-behavior:smooth}
    body{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f7fafc;color:#0f172a}
    .lang-zh .en{display:none}
    .lang-en .zh{display:none}
    .hero{background:linear-gradient(135deg,rgba(12,28,47,.82),rgba(16,107,113,.68)),url('/assets/shot1.jpg');background-size:cover;background-position:center}
    .card{background:white;border:1px solid #e5e7eb;border-radius:22px;box-shadow:0 12px 35px rgba(15,23,42,.07)}
    .gradient-title{background:linear-gradient(90deg,#2563eb,#14b8a6);-webkit-background-clip:text;background-clip:text;color:transparent}
  </style>
</head>
<body id="bodyTag" class="lang-en">
  <nav class="bg-white/95 backdrop-blur sticky top-0 z-50 border-b border-slate-200">
    <div class="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
      <a href="/" class="font-black text-xl text-blue-600">OutboundGuide.org</a>
      <div class="flex items-center gap-2 bg-slate-100 p-1 rounded-xl">
        <button onclick="setLang('en')" id="btn-en" class="px-3 py-1.5 rounded-lg bg-white shadow text-blue-600 font-bold text-sm">EN</button>
        <button onclick="setLang('zh')" id="btn-zh" class="px-3 py-1.5 rounded-lg text-slate-500 font-bold text-sm">中文</button>
      </div>
    </div>
  </nav>

  <header class="hero text-white">
    <div class="max-w-7xl mx-auto px-4 py-16">
      <div class="inline-flex gap-2 items-center bg-white/14 backdrop-blur rounded-full px-4 py-2 text-sm font-bold mb-4">
        <span class="en">{{ tag_en }}</span><span class="zh">{{ tag_zh }}</span>
      </div>
      <h1 class="text-4xl lg:text-5xl font-black mb-4">{{ title }}</h1>
      <p class="text-xl text-slate-100 max-w-3xl">{{ description }}</p>
      <div class="mt-4 text-sm text-slate-200">
        <span class="en">Generated: {{ generated_at }}</span><span class="zh">生成时间：{{ generated_at }}</span>
        {% if source_url %}| <a href="{{ source_url }}" target="_blank" class="underline">Source</a>{% endif %}
      </div>
    </div>
  </header>

  <main class="max-w-4xl mx-auto px-4 py-12">
    <div class="card p-8">
      {{ content_html }}
    </div>

    {% if related_guides %}
    <div class="mt-8">
      <h3 class="text-xl font-black mb-4"><span class="en">Related Guides</span><span class="zh">相关攻略</span></h3>
      <div class="grid sm:grid-cols-2 gap-4">
        {% for guide in related_guides %}
        <a href="{{ guide.url }}" class="card p-4 hover:shadow-lg transition">
          <div class="font-bold text-blue-600">{{ guide.title }}</div>
        </a>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </main>

  <footer class="bg-slate-950 text-slate-300 py-8 mt-12">
    <div class="max-w-7xl mx-auto px-4 text-center">
      <p class="text-sm"><span class="en">Auto-generated by Outbound Guide Bot</span><span class="zh">由 Outbound Guide Bot 自动生成</span></p>
      <p class="text-xs text-slate-500 mt-2">OutboundGuide.org - Non-official fan guide</p>
    </div>
  </footer>

  <script>
    function setLang(lang){const b=document.getElementById('bodyTag'),en=document.getElementById('btn-en'),zh=document.getElementById('btn-zh');if(lang==='zh'){b.className='lang-zh';zh.className='px-3 py-1.5 rounded-lg bg-white shadow text-blue-600 font-bold text-sm';en.className='px-3 py-1.5 rounded-lg text-slate-500 font-bold text-sm'}else{b.className='lang-en';en.className='px-3 py-1.5 rounded-lg bg-white shadow text-blue-600 font-bold text-sm';zh.className='px-3 py-1.5 rounded-lg text-slate-500 font-bold text-sm'}localStorage.setItem('lang',lang)};setLang(localStorage.getItem('lang')||'en');
  </script>
</body>
</html>'''

class PageGenerator:
    def __init__(self):
        self.template = Template(BASE_TEMPLATE)
        self.generated_files = []
    
    def _slugify(self, text):
        """生成 URL 友好的文件名"""
        text = re.sub(r'[^\w\s-]', '', text.lower())
        text = re.sub(r'[-\s]+', '-', text)
        return text[:50].strip('-')
    
    def _content_to_html(self, content):
        """将纯文本转换为简单 HTML"""
        if not content:
            return ""
        
        # 处理 bullet points
        lines = content.split('\n')
        html_lines = []
        in_list = False
        
        for line in lines:
            line = line.strip()
            if not line:
                if in_list:
                    html_lines.append('</ul>')
                    in_list = False
                html_lines.append('<br>')
                continue
            
            # 检测 bullet points
            if re.match(r'^[\*\-\+•]\s+', line):
                if not in_list:
                    html_lines.append('<ul class="list-disc pl-6 space-y-2 my-4">')
                    in_list = True
                item_text = re.sub(r'^[\*\-\+•]\s+', '', line)
                html_lines.append(f'<li class="text-slate-700">{item_text}</li>')
            elif re.match(r'^\d+[\.\)]\s+', line):
                if not in_list:
                    html_lines.append('<ol class="list-decimal pl-6 space-y-2 my-4">')
                    in_list = True
                item_text = re.sub(r'^\d+[\.\)]\s+', '', line)
                html_lines.append(f'<li class="text-slate-700">{item_text}</li>')
            else:
                if in_list:
                    html_lines.append('</ul>' if '<ul' in html_lines[-2] else '</ol>')
                    in_list = False
                html_lines.append(f'<p class="text-slate-700 leading-7 mb-4">{line}</p>')
        
        if in_list:
            html_lines.append('</ul>' if '<ul' in html_lines[-2] else '</ol>')
        
        return '\n'.join(html_lines)
    
    def generate_patch_notes_page(self, patches, lang='en'):
        """
        生成补丁日志页面
        patches: list of dict from steam_monitor
        """
        if not patches:
            return None
        
        # 构建内容
        content_parts = []
        for patch in patches[:5]:  # 最近5个补丁
            content_parts.append(f"## Patch {patch['version']} - {patch['date']}\n\n")
            content_parts.append(f"{patch['content_preview']}\n\n")
            if patch.get('url'):
                content_parts.append(f"[View full patch notes]({patch['url']})\n\n")
            content_parts.append("---\n\n")
        
        content = ''.join(content_parts)
        
        # 生成文件名
        latest_version = patches[0]['version'] if patches else 'latest'
        filename = f"patch-notes-auto-{latest_version}.html"
        filepath = os.path.join(SITE_REPO_PATH, lang, filename)
        
        # 渲染页面
        html = self.template.render(
            title=f"Patch Notes {latest_version}",
            description=f"Latest Outbound patch notes - {latest_version} and recent updates",
            tag_en="AUTO-UPDATED",
            tag_zh="自动更新",
            content_html=self._content_to_html(content),
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
            source_url="https://steamcommunity.com/app/2681030/allnews/",
            related_guides=[
                {"title": "Starter Guide", "url": f"/{lang}/starter-guide.html"},
                {"title": "All Guides", "url": "/#guides"}
            ]
        )
        
        # 保存
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        
        self.generated_files.append(filepath)
        print(f"[Generator] 生成补丁页面: {filepath}")
        return filepath
    
    def generate_reddit_guide_page(self, guide_data, lang='en'):
        """
        从 Reddit 帖子生成攻略页面
        guide_data: dict from reddit_monitor.extract_guide_content
        """
        # 构建内容
        content_parts = [guide_data['summary'], "\n\n"]
        
        if guide_data.get('tips'):
            content_parts.append("## Key Points\n\n")
            for tip in guide_data['tips']:
                content_parts.append(f"* {tip}\n")
            content_parts.append("\n")
        
        content_parts.append(f"\n\n*Source: Reddit u/{guide_data['author']}*")
        
        content = ''.join(content_parts)
        
        # 生成文件名
        slug = self._slugify(guide_data['title'])
        category = guide_data.get('category', 'general')
        filename = f"{category}-{slug}.html"
        filepath = os.path.join(SITE_REPO_PATH, lang, filename)
        
        # 避免覆盖已有文件
        counter = 1
        while os.path.exists(filepath):
            filename = f"{category}-{slug}-{counter}.html"
            filepath = os.path.join(SITE_REPO_PATH, lang, filename)
            counter += 1
        
        # 渲染页面
        html = self.template.render(
            title=guide_data['title'][:60],
            description=guide_data['summary'][:150],
            tag_en=f"FROM REDDIT | {guide_data['upvotes']} upvotes",
            tag_zh=f"来自 Reddit | {guide_data['upvotes']} 赞",
            content_html=self._content_to_html(content),
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
            source_url=guide_data['source_url'],
            related_guides=[
                {"title": "More Guides", "url": "/#guides"}
            ]
        )
        
        # 保存
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        
        self.generated_files.append(filepath)
        print(f"[Generator] 生成攻略页面: {filepath}")
        return filepath
    
    def update_index_stats(self, review_count, positive_percent):
        """
        更新首页的评价数据
        """
        index_path = os.path.join(SITE_REPO_PATH, "index.html")
        if not os.path.exists(index_path):
            print(f"[Generator] 找不到首页: {index_path}")
            return False
        
        try:
            with open(index_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 更新评价数 (中英文)
            content = re.sub(
                r'(\d{1,4}) reviews',
                f'{review_count} reviews',
                content
            )
            content = re.sub(
                r'(\d{1,4})条评价',
                f'{review_count}条评价',
                content
            )
            
            # 更新好评率
            content = re.sub(
                r'(\d{1,3})% positive',
                f'{positive_percent}% positive',
                content
            )
            content = re.sub(
                r'(\d{1,3})%好评',
                f'{positive_percent}%好评',
                content
            )
            
            with open(index_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"[Generator] 更新首页评价数据: {review_count} reviews, {positive_percent}% positive")
            return True
        except Exception as e:
            print(f"[Generator] 更新首页失败: {e}")
            return False
    
    def get_generated_files(self):
        return self.generated_files
